version: '2'
services:
    db:
        restart: always
        container_name: postgres_db
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: example
            POSTGRES_PASSWORD: example
            POSTGRES_DB: example